from typing import Protocol
from uuid import UUID

from .models import CompileOptions, Program


class ProgramsRepositoryPort(Protocol):
    async def get_all(self) -> list[Program]: ...

    async def get_by_name(self, program_name: str) -> Program | None: ...

    async def get_by_id(self, program_id: UUID) -> Program | None: ...

    async def create(self, program: Program) -> None: ...

    async def delete(self, program: Program) -> None: ...

    async def update(self, program: Program) -> None: ...


class CompilerPort(Protocol):
    def compile(self, cpp_code: str, options: CompileOptions) -> str: ...
    def get_mcus(self) -> list[str]: ...
