from typing import Protocol
from uuid import UUID

from .models import Program


class ProgramsRepositoryPort(Protocol):
    async def get_all(self) -> list[Program]: ...

    async def get_by_name(self, program_name: str) -> Program | None: ...

    async def get_by_id(self, program_id: UUID) -> Program | None: ...

    async def create(self, program: Program) -> None: ...

    async def delete(self, program: Program) -> None: ...

    async def update(self, program: Program) -> None: ...
